### ISSUE TITLE
PHPStan output is missing notFileSpecificErrors

### ISSUE THREAD

**Issue by ondrejmirtes** [taptima/phalyfusion#12]
The tool should output everything the [JSON formatter](https://github.com/phpstan/phpstan-src/blob/master/src/Command/ErrorFormatter/JsonErrorFormatter.php) outputs.

**Comment by ondrejmirtes** [comment]
(Sorry, sent it prematurely.)

In each JSON there's a top-level section `errors` which can contain messages like [unmatched ignored errors](https://phpstan.org/user-guide/ignoring-errors#reporting-unused-ignores), internal errors etc.

**Comment by koninka** [comment]
@ondrejmirtes thx! I'll check it
